<h3>Login:</h3>
<br />
<?php if ($this->error) : ?>
<p>Usuário ou senha inválidos</p>
<?php endif;?>

<?php 
$form = $this->form;
$form->setAttribute('action', $this->url('sonuser-auth'));
$form->prepare();

echo $this->form()->openTag($form);
foreach ($form->getElements() as $el) :
        ?>
        <div class="form-group">
            <?php echo $this->formRow($el); ?>
        </div>
        <?php
endforeach;
echo $this->form()->closeTag();
?>