<h3>Novo Privilege</h3>

<br />

<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('sonacl-admin/default',array('controller'=>'privileges','action'=>'new')));

$form->prepare();
echo $this->form()->openTag($form);
foreach ($form->getElements() as $el) :
        ?>
        <div class="form-group">
            <?php echo $this->formRow($el); ?>
        </div>
        <?php
endforeach;
echo $this->form()->closeTag();
?>